### ISSUE TITLE
vector index in "for" loop must be integral (Phish::rec$path)

### ISSUE THREAD

**Issue by binups** [initconf/smtp-url-analysis#1]
this script is getting error

error in smtp-url-analysis/scripts/./smtp-malicious-indicators.bro, line 150: vector index in "for" loop must be integral (Phish::rec$path)
vector index in "for" loop must be integral (Phish::rec$path)
error in smtp-url-analysis/scripts/./smtp-malicious-indicators.bro, line 152: not an index type (Phish::rec$path[path])

**Comment by initconf** [comment]
Ah! I see the issue now. Do you have a pcap you can share which reproduces
this issue ?

Thanks
Aashish
