### ISSUE TITLE
Use smtp-url-analysis with workers 

### ISSUE THREAD

**Issue by puma2004** [initconf/smtp-url-analysis#3]
Hi, I have used **smtp-url-analysis** for a year in **stand alone** and I am very happy with the result, it works great !, now for high traffic needs I have compiled bro with pf_ring and I am using several workers, but I can not make **smtp-url-analysis** .
This is the error in question:

> error in /opt/bro-2.6.2/share/bro/site/smtp-url-analysis/scripts/./distribute-smtp-urls-workers.bro, line 17: "redef" used but not previously defined (Cluster :: manager2worker_events)
> error in /opt/bro-2.6.2/share/bro/site/smtp-url-analysis/scripts/./distribute-smtp-urls-workers.bro, line 18: "redef" used but not previously defined (Cluster :: worker2manager_events)

When I go back to **stand alone mode**, everything works perfectly, but in cluster mode it fails.

Line 17 and 18 contain the following information:
```
redef Cluster :: manager2worker_events + = / Phish :: m_w_smtpurls_add | Phish :: m_w_add_url_to_bloom /;
redef Cluster :: worker2manager_events + = / Phish :: w_m_smtpurls_new | Phish :: w_m_url_click | Phish :: w_m_url_click_in_bloom /;

```
I guess the value that needs to be changed is "redef Cluster :: manager2worker_events", but I do not know which one

Thank you!

**Comment by initconf** [comment]
Hello Puma,  Sorry for the issue - Somehow I missed your ticket 

OK I have new updated version which runs with zeek-3.x.x now ! If you'd want to try this out too - thanks !
