### ISSUE TITLE
smtp_clicked_urls.log is not created 

### ISSUE THREAD

**Issue by andrpetr** [initconf/smtp-url-analysis#4]
Running bro version 2.5.2 smtp_clicked_urls.log is not created. I am testing it on tests/Traces/.*pcap's and also on live sensor. 
i do get smtpurl_links.log with bunch of links but not smtp_clicked_urls.log even after clicking on them

**Comment by initconf** [comment]
Sorry for the issue - Somehow I missed your ticket 

OK I have new updated version which runs with zeek-3.x.x now ! If you'd want to try this out too - thanks !
