### ISSUE TITLE
smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

### ISSUE THREAD

**Issue by scotharris** [initconf/smtp-url-analysis#5]
Running Zeek 3.0 on Centos 8.

Used zkg to attemp install of smtp-malicious-indicators.bro package.

Errors found in zkg.test_command.stderr during install test

smtp-url-analysis.BogusSiteURL ... failed
  % 'bro -r $TRACES/BogusSiteURL-example.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.BogusSiteURL/BogusSiteURL.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

smtp-url-analysis.DottedURL ... failed
  % 'bro -r $TRACES/DottedURL.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.DottedURL/DottedURL.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

smtp-url-analysis.FileDownload ... failed
  % 'bro -r $TRACES/FileDownload-example.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.FileDownload/FileDownload.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

smtp-url-analysis.HTTPSensitivePOST ... failed
  % 'bro -r $TRACES/HTTPSensitivePOST.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.HTTPSensitivePOST/HTTPSensitivePOST.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

smtp-url-analysis.HTTP_SensitivePasswd ... failed
  % 'bro -r $TRACES/HTTP_SensitivePasswd.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.HTTP_SensitivePasswd/HTTP_SensitivePasswd.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

smtp-url-analysis.SensitiveURI ... failed
  % 'bro -r $TRACES/SensitiveURI.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.SensitiveURI/SensitiveURI.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

smtp-url-analysis.smtp-attachment ... failed
  % 'bro -r $TRACES/smtp-attachment.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.smtp-attachment/smtp-attachment.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

smtp-url-analysis.smtp-malicious-indicators ... failed
  % 'bro -r $TRACES/smtp-malicious-indicators.pcap ../../../scripts /home/zeek/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis/tests/.tmp/smtp-url-analysis.smtp-malicious-indicators/smtp-malicious-indicators.bro' failed unexpectedly (exit code 1)
  % cat .stderr
  warning in ./../../../scripts/./base-vars.bro, line 64: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./base-vars.bro, line 279: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./email-alerts-batch.bro, line 99: deprecated (bro_done): Remove in v3.1: use zeek_done
  warning in ./../../../scripts/./log-smtp-urls.bro, line 38: deprecated (bro_init): Remove in v3.1: use zeek_init
  warning in ./../../../scripts/./log-clicked-urls.bro, line 30: deprecated (bro_init): Remove in v3.1: use zeek_init
  error in ./../../../scripts/./smtp-malicious-indicators.bro, line 29: syntax error, at or near "&"

8 of 8 tests failed

**Comment by initconf** [comment]
Sorry for the issue - Somehow I missed your ticket 

OK I have new updated version which runs with zeek-3.x.x now ! If you'd want to try this out too - thanks !
