### ISSUE TITLE
error: "zeek/initconf/smtp-url-analysis" tests failed

### ISSUE THREAD

**Issue by michaelkasede** [initconf/smtp-url-analysis#6]
Hi 
I am trying to install the **smtp-url-analysis** package on Zeek v3.0.3 but I get a strange error:
`michael@Ubuntu:~$ zkg install zeek/initconf/smtp-url-analysis`
`The following packages will be INSTALLED:`
 ` zeek/initconf/smtp-url-analysis (master)`
`Proceed? [Y/n] Y`
`Running unit tests for "zeek/initconf/smtp-url-analysis"`
`error: "zeek/initconf/smtp-url-analysis" tests failed, inspect contents of /home/michael/.zkg/testing``/smtp-url-analysis for details, especially any "zkg.test_command.{stderr,stdout}" files within /home/michael/.zkg/testing/smtp-url-analysis/clones/smtp-url-analysis`
`Proceed to install anyway? [N/y] n`
`Abort.`

Can you help me understand this error and how to fix it?

**Comment by initconf** [comment]
Sorry, this works until 2.5.5 since 2.6.x onwards zeek has a new underlying cluster framework based on broker. 

I need to forward port this to use new broker-framework -  haven't got to it just yet. Hopefully very soon!

**Comment by michaelkasede** [comment]
Ohh great. Great job on creating the package. I truly believe it's a must-have for any zeek deployment.

**Comment by initconf** [comment]
OK I have new updated version which runs with zeek-3.x.x now ! If you'd want to try this out too - thanks !
